Repository MTES-MCT/resorption-bidonvilles, pull requests merged in 2021-05, with the labels that each got.

#121 #patch (?) Migration vers l'API de soliguide
  src/js/app/components/map/map.js
  src/js/app/pages/dashboard/POIView.vue
  src/js/app/pages/dashboard/dashboard.js
Labels: [validé]

#130 #patch Statistiques privés - Ajout de la date de référence pour les résorptions
  src/js/app/pages/PrivateStats/KeyMetric.vue
  src/js/app/pages/PrivateStats/index.vue
Labels: [en attente de review]

#126 #patch (998) Correction de la latence de màj des mises en production
  public/index.html
Labels: [qa]

#124 #patch (834) date de signalement site obligatoire plutôt que date d'installation
  cypress/fixtures/shantytowns.json
  src/js/app/components/TownForm/TownFormPanelCharacteristics.vue
  src/js/app/components/TownForm/inputs/InputBuiltAt.vue
  src/js/app/components/TownForm/inputs/InputDeclaredAt.vue
Labels: [qa]

#131 #patch (906) Suppression d'une route inutile
  src/js/helpers/api/town.js
Labels: [qa]

#148 #patch (1028) Changer le wording "stats privées" par "Tableau de bord"
  src/js/app/layouts/navbar/items.js
  src/js/app/pages/PrivateStats/LeftColumn.vue
  src/js/app/router.js
Labels: [validé]

#147 #patch (945) Ajouter sur la page de connexion un lien pour s'inscrire à la plateforme
  src/js/app/pages/signin/signin.pug
Labels: [validé]

#146 #minor (1054) Bandeau event sur plateforme
  src/js/app/components/EventBannerPlatform/index.vue
  src/js/app/components/FundingRequestBanner/index.vue
  src/js/app/pages/TownsList/TownsList.vue
  src/js/app/pages/plans.list/plans.list.js
  src/js/app/pages/plans.list/plans.list.pug
Labels: [validé]

#142 #patch (1013) Ajout d'un graphique avec l'évolution du nombre d'habitants
  src/js/app/pages/PrivateStats/index.vue
Labels: [validé]

#151 #patch (953) Rétablir la suppression de ligne de financements
  src/js/app/components/form/input/planFunding/planFundingRow/planFundingRow.pug
Labels: [validé]
