Repository MTES-MCT/resorption-bidonvilles, pull requests merged in 2021-09, with the labels that each got.

#271 #patch (1180) Correction nombre de commentaires + tag covid
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsLeftColumn.vue
  packages/frontend/src/js/app/pages/TownDetails/ui/CommentBlock.vue
Labels: [en attente de review]

#268 #minor (921) Ajout d'un scroll sur les tableaux d'historique de population trop longs
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsPanelPeople.vue
Labels: [validé]

#270 #minor (1177) Fix date for closing event in Town Changelog
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsHistorySidePanel.vue
Labels: [validé]

#269 #patch (1174) Mettre le nom du demandeur d'accès en bold dans les mails
  packages/api/server/mails/dist/admin_access_activated.html
  packages/api/server/mails/dist/admin_access_expired.html
  packages/api/server/mails/dist/admin_new_request_notification.html
  packages/api/server/mails/dist/admin_request_pending_reminder_1.html
  packages/api/server/mails/dist/admin_request_pending_reminder_2.html
  packages/api/server/mails/src/admin_access_activated.mjml
  packages/api/server/mails/src/admin_access_expired.mjml
  packages/api/server/mails/src/admin_new_request_notification.mjml
  packages/api/server/mails/src/admin_request_pending_reminder_1.mjml
  packages/api/server/mails/src/admin_request_pending_reminder_2.mjml
Labels: [validé]

#264 #patch (1120) Amélioration suivi des évènements par Matomo
  packages/frontend/src/js/app/components/TownForm/TownForm.vue
  packages/frontend/src/js/app/components/quickview/quickview.js
  packages/frontend/src/js/app/pages/Contact/index.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsActorThemesModal.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCloseModal.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCovidCommentsSidePanel.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsInviteActorModal.vue
  packages/frontend/src/js/app/pages/dashboard/POIView.vue
  packages/frontend/src/js/app/pages/plans.create/plans.create.js
  packages/frontend/src/js/app/pages/plans.edit/plans.edit.js
  packages/frontend/src/js/app/pages/plans.marks/plans.marks.js
Labels: [validé]

#263 #patch (1082) 2e champ mail pour éviter erreur de saisie
  packages/api/server/middlewares/validators/createContact.js
  packages/frontend/src/js/app/messages/bg/contactPage.json
  packages/frontend/src/js/app/messages/en/contactPage.json
  packages/frontend/src/js/app/messages/fr/contactPage.json
  packages/frontend/src/js/app/messages/ro/contactPage.json
  packages/frontend/src/js/app/pages/Contact/index.vue
Labels: [qa]

#275 #minor (1210) Passage à Typescript
  packages/api/.dockerignore
  packages/api/.gitignore
  packages/api/package.json
  packages/api/server/index.ts
  packages/api/tsconfig.json
  packages/api/yarn.lock
Labels: [validé]

#267 #patch (1202) Ajouter un bouton sur la fiche utilisateur pour attribuer un accès intervenant
  packages/api/db/migrations/001202-01-alter-table-organization_types-add-uid.js
  packages/api/server/controllers/organizationController.js
  packages/api/server/loaders/routesLoader.js
  packages/api/server/models/organizationModel.js
  packages/api/server/models/userModel.js
  packages/frontend/src/js/app/pages/UserValidate/index.vue
  packages/frontend/src/js/helpers/api/organization.js
Labels: [en attente de review]

#279 # patch (1223) Permission mal calculées pour une fiche site rattaché à un arrondissement
  packages/api/db/migrations/001223-01-alter-localized_organizations-add-city_main.js
  packages/api/server/models/userModel.js
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsHeader.vue
  packages/frontend/src/js/app/pages/TownsList/TownsList.vue
Labels: [en attente de review]

#280 #patch (1224) Correction de l'export de la liste des sites
  packages/api/db/models/stats_exports.js
Labels: [en attente de review]

#291 #patch (1228) Renommer DRETS en DREETS
  packages/api/db/migrations/001228-01-rename-drets-to-dreets.js
Labels: [validé]

#296 #patch (1219) Mail Nouveau commentaire : ajout du message
  packages/api/server/mails/dist/user_new_comment.html
  packages/api/server/mails/dist/user_new_comment.text
  packages/api/server/mails/mails.js
  packages/api/server/mails/src/user_new_comment.mjml
Labels: [validé]

#294 #patch (1072) Ajout d'une colonne code INSEE dans l'export des sites
  packages/api/server/controllers/townController.js
Labels: [validé]

#293 #patch (1216) Remplaces DINSIC par DINUM sur la page des mentions légales
  packages/frontend/src/js/app/pages/legalMentions/legalMentions.pug
Labels: [qa]

#283 #patch (1215) Export de la liste des utilisateurs pour les admins nationaux
  packages/api/package.json
  packages/api/server/controllers/userController.js
  packages/api/server/loaders/routesLoader.js
  packages/api/server/models/userModel.js
  packages/api/yarn.lock
  packages/frontend/src/js/app/pages/UserList/UserListHeader/index.vue
  packages/frontend/src/js/helpers/api/user.js
Labels: [qa]

#289 #patch (831) Barrer les cartes des sites fermés
  packages/frontend/src/js/app/pages/TownsList/TownCard.vue
Labels: [qa]

#288 #patch (1086) Correction nom des images departements
  packages/frontend/public/img/departements/01.svg
  packages/frontend/public/img/departements/02.svg
  packages/frontend/public/img/departements/03.svg
  packages/frontend/public/img/departements/04.svg
  packages/frontend/public/img/departements/05.svg
  packages/frontend/public/img/departements/06.svg
  packages/frontend/public/img/departements/07.svg
  packages/frontend/public/img/departements/08.svg
  packages/frontend/public/img/departements/09.svg
Labels: [validé]

#287 #patch (1218) Ajout lien guide de l'administrateur
  packages/frontend/public/doc/guide_de_l_administrateur.pdf
  packages/frontend/src/js/app/pages/UserList/UserListHeader/index.vue
Labels: [validé]

#281 #patch (1225) Fix filtering of activities on history
  packages/frontend/src/js/app/pages/History/History.vue
  packages/frontend/src/js/app/store/modules/activities.js
Labels: [validé]

#285 #minor (1132) Légende sous le graphique Nombre d'habitants en bidonvilles
  packages/frontend/src/js/app/pages/PrivateStats/index.vue
Labels: [validé]

#302 #minor (1212) Ajout de la mention "Site avec objectif..." sur notif Mattermost lors de la fermeture d'un site
  packages/api/server/utils/mattermost.js
Labels: [validé]

#309 #patch (1213) Ajout d'un lien de désabonnement aux récaps hebdos
  packages/api/db/migrations/001213-001-alter-users-add-column-subscribed_to_summary.js
  packages/api/server/controllers/userController.js
  packages/api/server/mails/src/activity_summary.mjml
  packages/api/server/mails/src/common/summary_full_activities.mjml
  packages/api/server/middlewares/validators/editUser.js
  packages/api/server/models/userModel/index.js
  packages/frontend/src/js/app/pages/Account/AccountEdit/AccountEdit.vue
  packages/frontend/src/js/app/pages/Account/AccountRead/AccountRead.vue
Labels: [en attente de review]

#307 #minor (1230) Affiche les retours à la lignes dans les comentaires sur le journal des sites
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsComments.vue
Labels: [validé]

#295 #minor (1171) Setup weekly mail report
  packages/api/db/migrations/001213-001-alter-users-add-column-subscribed_to_summary.js
  packages/api/package.json
  packages/api/server/app.ts
  packages/api/server/config.js
  packages/api/server/controllers/userController.js
  packages/api/server/index.ts
  packages/api/server/loaders/agendaJobsLoader.ts
  packages/api/server/loaders/index.ts
  packages/api/server/mails/mails.js
  packages/api/server/mails/src/activity_summary.mjml
  packages/api/server/mails/src/common/attributes.mjml
  packages/api/server/mails/src/common/styles.mjml
  packages/api/server/mails/src/common/summary.mjml
  packages/api/server/mails/src/common/summary_footer.mjml
  packages/api/server/mails/src/common/summary_full_activities.mjml
  packages/api/server/middlewares/validators/editUser.js
  packages/api/server/models/activityModel/get.ts
  packages/api/server/models/activityModel/index.ts
  packages/api/server/models/activityModel/types/ActivityDepartementalSummary.ts
  packages/api/server/models/activityModel/types/ActivityNationalSummary.ts
  packages/api/server/models/index.js
  packages/api/server/models/permissionModel/index.js
  packages/api/server/models/permissionModel/types/Permission.ts
  packages/api/server/models/permissionModel/types/Permissions.ts
  packages/api/server/models/permissionModel/types/permissionGeographicLevel.ts
  packages/api/server/models/permissionModel/types/permissionOption.ts
  packages/api/server/models/userModel/index.js
  packages/api/server/models/userModel/types/User.ts
  packages/api/server/models/userModel/types/userLocationType.ts
  packages/api/server/models/userModel/types/userStatus.ts
  packages/api/server/services/activitySummary/index.ts
  packages/api/server/services/activitySummary/sendAll.ts
  packages/api/server/services/activitySummary/sendDepartementalSummary.ts
  packages/api/server/services/activitySummary/sendNationalSummary.ts
  packages/api/server/services/activitySummary/sendRegionalSummary.ts
  packages/api/yarn.lock
  packages/frontend/src/js/app/pages/Account/AccountEdit/AccountEdit.vue
  packages/frontend/src/js/app/pages/Account/AccountRead/AccountRead.vue
Labels: [validé]

#311 #patch (1244) Passer la carte du formulaire d'ajout/édition de sites en satelitte par défaut
  packages/frontend/src/js/app/components/ui/Map.vue
Labels: [validé]

#315 #patch (1236) Masquer "Ne jamais envoyer un accès..." si une demande a déja été envoyée
  packages/frontend/src/js/app/pages/UserValidate/index.vue
Labels: [en attente de review]

#314 #patch (1102) Affichage d'un message lorsqu'on est redirigé sur la page de connexion
  packages/frontend/src/js/app/pages/SignIn/index.vue
  packages/frontend/src/js/app/router.js
Labels: [en attente de review]

#310 #minor (1183) - affichage des sites fermés sur la carte
  packages/frontend/src/js/app/components/map/map.js
  packages/frontend/src/js/app/components/quickview/quickview.pug
  packages/frontend/src/js/app/pages/dashboard/dashboard.scss
Labels: [en attente de review]

#319 #minor (1240) ajout d'une nuance concernant l’accès à l’eau sur la carto
  packages/frontend/public/img/water-to-improve.png
  packages/frontend/src/js/app/components/map/map.js
  packages/frontend/src/js/app/pages/TownDetails/formatLivingConditions.js
Labels: [validé]
