Repository MTES-MCT/resorption-bidonvilles, pull requests merged in 2021-08, with the labels that each got.

#256 #minor (1138) Amélioration du tracking du profil de l'utilisateur connecté
  packages/frontend/src/js/matomo/matomo.js
Labels: [validé]

#257 #patch (1196) Ecran de connexion, pas adapté pour du 13 pouces
  packages/frontend/src/js/app/components/LoginLayout/index.vue
Labels: [qa]

#262 #patch (1200) Bannière sur le webinaire accès à l'eau
  packages/frontend/src/js/app/components/EventBannerPlatform/index.vue
  packages/frontend/src/js/app/components/EventBannerWaterAccess/index.vue
  packages/frontend/src/js/app/components/ui/Link.vue
  packages/frontend/src/js/app/pages/LandingPage/LandingEventBanner.vue
  packages/frontend/src/js/app/pages/LandingPage/assets/banniere_access_eau.jpg
  packages/frontend/src/js/app/pages/LandingPage/assets/banniere_vaccin.png
  packages/frontend/src/js/app/pages/TownsList/TownsList.vue
  packages/frontend/src/js/app/pages/plans.list/plans.list.js
  packages/frontend/src/js/app/pages/plans.list/plans.list.pug
Labels: [en attente de review]

#261 #patch (1194) Ajout de traductions à la landing page
  packages/frontend/src/js/app/messages/bg/contactPage.json
  packages/frontend/src/js/app/messages/bg/landingPage.json
  packages/frontend/src/js/app/messages/en/contactPage.json
  packages/frontend/src/js/app/messages/en/landingPage.json
  packages/frontend/src/js/app/messages/fr/contactPage.json
  packages/frontend/src/js/app/messages/ro/contactPage.json
  packages/frontend/src/js/app/messages/ro/landingPage.json
  packages/frontend/src/js/app/pages/LandingPage/index.vue
Labels: [en attente de review]
