Repository MTES-MCT/resorption-bidonvilles, pull requests merged in 2021-07, with the labels that each got.

#190 #patch (993) Rendre les commentaires Covid accessibles à tous
  packages/api/server/models/shantytownModel.js
Labels: [en attente de review]

#191 #patch (1143) La fiche d'un site ne se met pas à jour en cas de fermeture ou nouveau commentaire COVID
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCloseModal.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCovidCommentsSidePanel.vue
  packages/frontend/src/js/app/store/index.js
Labels: [en attente de review]

#192 #patch (1144) Un message d'erreur apparaît au reset du formulaire d'ajout de commentaire COVID
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCovidCommentsSidePanel.vue
Labels: [en attente de review]

#189 #patch (1111) Réintégrer les origines des habitants à l'historique des modifications
  packages/api/server/models/shantytownModel.js
Labels: [en attente de review]

#198 #patch (1085) Correction du nombre d'utilisateurs pour chaque département dans le TB
  packages/api/server/models/statsModel.js
Labels: [validé]

#197 #patch (1077) Rendre obligatoire le numéro de téléphone sur les demandes d'info et demande d'accès
  packages/api/server/middlewares/validators/createContact.js
  packages/frontend/src/js/app/messages/en/contactPage.json
  packages/frontend/src/js/app/messages/fr/contactPage.json
  packages/frontend/src/js/app/pages/Contact/index.vue
Labels: [validé]

#186 #minor (946) Fusion des Direccte et DDCS
  packages/api/db/migrations/000946-01-create_organization_types_drets_ddets.js
  packages/api/db/migrations/000946-02-populate_organizations_with_drets_ddets.js
  packages/api/db/migrations/000946-03-transfer-users-to-ddets-drets.js
Labels: [validé]

#201 #patch (1146) Correction de l'export pour les villes à arrondissement
  packages/api/server/controllers/townController.js
Labels: [en attente de review]

#196 #minor (1103) Mise à jour du parcours d'invitation d'intervenant(e)s déjà utilisateurs
  packages/api/server/controllers/townController/addActor.js
  packages/api/server/mails/dist/shantytown_actor_notification.html
  packages/api/server/mails/dist/shantytown_actor_notification.subject.text
  packages/api/server/mails/dist/shantytown_actor_notification.text
  packages/api/server/mails/mails.js
  packages/api/server/mails/src/shantytown_actor_notification.mjml
  packages/frontend/src/js/app/components/ui/Modal.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsActorThemesModal.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsInviteActorModal.vue
  packages/frontend/src/js/app/store/index.js
Labels: [en attente de review]

#203 #patch (1149) Ajout de l'email/téléphone + replyTo pour les messages de contact
  packages/api/server/controllers/contactController.js
  packages/api/server/mails/dist/admin_contact_message.html
  packages/api/server/mails/dist/admin_contact_message.text
  packages/api/server/mails/mails.js
  packages/api/server/mails/src/admin_contact_message.mjml
Labels: [en attente de review]

#204 #patch (1150) Corriger l'export au-delà de la commune
  packages/api/server/controllers/townController.js
Labels: [en attente de review]

#205 #patch (1151) Correction d'une erreur sur la page de l'historique des activités
  packages/api/server/models/shantytownModel.js
Labels: [en attente de review]

#176 #patch (1104) Initialisation d'un workflow de déploiement
  .github/workflows/deploy-qa.yml
Labels: [validé]

#202 #patch (1094) Revue de l'UI pour la date de dernière mise à jour + changement du tri par défaut des sites
  packages/frontend/src/js/app/components/ui/Tag.vue
  packages/frontend/src/js/app/pages/TownsList/TownCard.vue
  packages/frontend/src/js/app/store/index.js
Labels: [validé]

#212 (1119) PR feedback
  packages/frontend/src/js/app/pages/launcher/launcher.js
  packages/frontend/src/js/matomo/matomo.js
Labels: [en attente de review]

#210 #patch (1123) Ajouter les commentaires covid en lecture dans le journal du site
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
Labels: [qa]

#222 (1122) PR feedback
  packages/frontend/src/js/app/pages/LandingPage/LandingPageNewsletter.vue
Labels: [validé]

#217 #patch (1160) Fix validation of pop_minors and pop_couples
  packages/frontend/src/js/app/components/TownForm/inputs/InputPopulation.vue
Labels: [qa]

#227 #patch (1176) Mise à jour de la courbe des stats publiques
  packages/frontend/src/js/app/pages/PublicStats/index.vue
Labels: [validé]

#224 #patch (1131) Placeholder de l'espace message dans le journal du site et texte à gauche modifiés
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsNewComment.vue
Labels: [validé]

#225 #patch (1152) Sauvegarder la date et heure de dernière connexion
  packages/api/db/migrations/001152-add-last-access-to-users.js
  packages/api/server/middlewares/authMiddleware.js
  packages/api/server/models/userModel.js
Labels: [validé]

#226 #patch (1157) Ajout d'un placeholder dans la zone de comentaires Covid-19 sur la vue TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCovidCommentsSidePanel.vue
Labels: [qa]

#228 #patch (1182) Training invitation message modified
  packages/frontend/src/js/app/pages/LandingPage/LandingTutorialBanner.vue
Labels: [en attente de review]

#220 #patch (1107+ 1121) - Redirection systématique vers page d'invitation + origine mentionnée dans les notifications Mattermost
  packages/api/server/controllers/inviteController.js
  packages/api/server/mails/mails.js
  packages/api/server/middlewares/validators/invite.js
  packages/frontend/src/js/app/components/ui/Form/input/TextArea.vue
  packages/frontend/src/js/app/components/ui/Icon.vue
  packages/frontend/src/js/app/pages/Contact/index.vue
  packages/frontend/src/js/app/pages/Invitation/index.vue
Labels: [en attente de review]

#234 (1133) Ajout du tag "Objectif résorption 2021 par la Préfecture"
  packages/api/db/migrations/001133-add-resorption_target-to-shantytowns.js
  packages/api/server/models/shantytownModel.js
  packages/frontend/src/js/app/components/ui/Tag.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsHeader.vue
  packages/frontend/src/js/app/pages/TownsList/TownCard.vue
  packages/frontend/src/js/app/pages/TownsList/TownsList.vue
  packages/frontend/src/js/app/pages/TownsList/filterShantytowns.js
  packages/frontend/src/js/app/store/index.js
Labels: [validé]

#233 (1095) Ajouter dans l'export Excel une colonne avec les intervenants
  packages/api/server/controllers/townController.js
  packages/frontend/src/js/app/components/export2/Export.vue
Labels: [validé]

#232 (1147) Permettre la validation via l'interface des profils de rôle "Intervenant"
  packages/api/server/permissions_description.js
Labels: [validé]

#236 (1085) Popup nouveauté vaccination
  packages/api/assets/changelog/1.8.0/item_1.gif
  packages/api/assets/changelog/1.8.0/item_2.jpg
  packages/api/db/migrations/001185-01-popup_26_07_2021.js
Labels: [validé]

#230 #patch (1178) Activation du mode "history" pour les URLs sans "/#" en préfixe
  packages/api/server/mails/README.md
  packages/frontend/cypress/integration/towns.create-edit-delete-fromFullToMin.spec.js
  packages/frontend/cypress/integration/towns.create-edit-delete-fromMinToFull.spec.js
  packages/frontend/cypress/integration/towns.create-edit-delete-fromMinToMin.spec.js
  packages/frontend/cypress/support/commands/signinAs.js
  packages/frontend/src/js/app/pages/Contact/SocialShare.vue
  packages/frontend/src/js/app/pages/signin/signin.js
  packages/frontend/src/js/app/pages/signin/signin.pug
  packages/frontend/src/js/app/pages/users.activate/users.activate.js
  packages/frontend/src/js/app/router.js
Labels: [qa]

#238 #patch (1188) Les activités datant d'hier sont marquées comme datant "d'aujourd'hui"
  packages/frontend/src/js/app/components/ActivityCard/utils/formatDate.js
Labels: [validé]

#240 #patch (1190) Reduire le nombre d'informations remontées dans le fil d'actualité
  packages/frontend/src/js/app/components/ActivityCard/ActivityCardBody/ActivityCardBodyShantytownUpdated.vue
  packages/frontend/src/js/app/pages/TownsList/TownsList.vue
Labels: [validé]

#241 #patch (1191) Le texte "Trier par" est manquant sur la liste des sites
  packages/frontend/src/js/app/pages/TownsList/TownsList.vue
  packages/frontend/src/js/app/pages/TownsList/TownsListSort/TownsListSort.vue
Labels: [validé]

#237 #patch (1187) Setup mail blacklisting
  packages/api/server/config.js
  packages/api/server/controllers/townController.js
  packages/api/server/models/userModel.js
  packages/api/server/services/shantytown/create.js
  packages/api/test/suites/server/controllers/townController/close.spec.js
Labels: [validé]

#235 (964, 1050, 1127, 1129) Redesign page de connexion + activation + demande mdp + reset mdp
  packages/frontend/cypress/support/commands/signinAs.js
  packages/frontend/src/js/app/components/LoginLayout/LoginNavBar/LoginNavBarLink.vue
  packages/frontend/src/js/app/components/LoginLayout/LoginNavBar/NavBarLogo.vue
  packages/frontend/src/js/app/components/LoginLayout/LoginNavBar/index.vue
  packages/frontend/src/js/app/components/LoginLayout/PasswordInfo.vue
  packages/frontend/src/js/app/components/LoginLayout/assets/Marianne.svg
  packages/frontend/src/js/app/components/LoginLayout/index.vue
  packages/frontend/src/js/app/components/ui/Form/input/PasswordInput.vue
  packages/frontend/src/js/app/components/ui/Form/input/TextInput.vue
  packages/frontend/src/js/app/components/ui/registerGlobalComponents.js
  packages/frontend/src/js/app/pages/SignIn/index.vue
  packages/frontend/src/js/app/pages/UserActivate/index.vue
  packages/frontend/src/js/app/pages/UserRequestNewPassword/index.vue
  packages/frontend/src/js/app/pages/UserSetNewPassword/index.vue
  packages/frontend/src/js/app/pages/signin/signin.js
  packages/frontend/src/js/app/pages/signin/signin.pug
  packages/frontend/src/js/app/pages/signin/signin.scss
  packages/frontend/src/js/app/pages/signin/signin.vue
  packages/frontend/src/js/app/pages/users.activate/users.activate.js
  packages/frontend/src/js/app/pages/users.activate/users.activate.pug
  packages/frontend/src/js/app/pages/users.activate/users.activate.scss
  packages/frontend/src/js/app/pages/users.activate/users.activate.vue
  packages/frontend/src/js/app/pages/users.requestNewPassword/users.requestNewPassword.js
  packages/frontend/src/js/app/pages/users.requestNewPassword/users.requestNewPassword.pug
  packages/frontend/src/js/app/pages/users.requestNewPassword/users.requestNewPassword.scss
  packages/frontend/src/js/app/pages/users.requestNewPassword/users.requestNewPassword.vue
  packages/frontend/src/js/app/pages/users.setNewPassword/users.setNewPassword.js
  packages/frontend/src/js/app/pages/users.setNewPassword/users.setNewPassword.pug
  packages/frontend/src/js/app/pages/users.setNewPassword/users.setNewPassword.scss
  packages/frontend/src/js/app/pages/users.setNewPassword/users.setNewPassword.vue
  packages/frontend/src/js/app/router.js
Labels: [validé]

#242 #patch (1170) Fix some links reputation in emails
  packages/api/server/mails/dist/admin_access_activated.html
  packages/api/server/mails/dist/admin_access_activated.text
  packages/api/server/mails/dist/admin_new_request_notification.html
  packages/api/server/mails/dist/admin_new_request_notification.text
  packages/api/server/mails/src/common/formation_cta_other.mjml
Labels: [validé]

#243 #patch (1029) Ouverture du Tableau de bord aux "national_establisment"
  packages/api/db/migrations/001029-01-alter-permissions-stats.read.js
  packages/frontend/src/js/app/layouts/navbar/items.js
Labels: [validé]

#244 #patch (1042) Changement de placeholder pour la barre de recherche de sites
  packages/frontend/src/js/app/components/GeoSearchbar/GeoSearchbar.vue
Labels: [validé]

#245 #patch (1114) Add an option 'register to newsletter' on Contact
  packages/api/server/config/contact_request_types.js
  packages/api/server/controllers/contactController.js
  packages/api/server/mails/dist/contact_newsletter_registration.html
  packages/api/server/mails/dist/contact_newsletter_registration.subject.text
  packages/api/server/mails/dist/contact_newsletter_registration.text
  packages/api/server/mails/mails.js
  packages/api/server/mails/src/contact_newsletter_registration.mjml
  packages/frontend/src/js/app/messages/bg/contactPage.json
  packages/frontend/src/js/app/messages/bg/footer.json
  packages/frontend/src/js/app/messages/bg/landingPage.json
  packages/frontend/src/js/app/messages/en/contactPage.json
  packages/frontend/src/js/app/messages/en/footer.json
  packages/frontend/src/js/app/messages/en/landingPage.json
  packages/frontend/src/js/app/messages/fr/contactPage.json
  packages/frontend/src/js/app/messages/fr/landingPage.json
  packages/frontend/src/js/app/messages/ro/contactPage.json
  packages/frontend/src/js/app/messages/ro/footer.json
  packages/frontend/src/js/app/messages/ro/landingPage.json
  packages/frontend/src/js/app/pages/Contact/index.vue
Labels: [validé]
