Repository MTES-MCT/resorption-bidonvilles, pull requests merged in 2021-06, with the labels that each got.

#152 #patch (1041) Correction des messages d'erreur concernant la date de signalement
  packages/frontend/src/js/app/components/TownForm/inputs/InputBuiltAt.vue
Labels: [validé]

#168 (1064) Wording
  packages/frontend/src/js/app/messages/fr/contactPage.json
Labels: [validé]

#164 #patch (1076) Amélioration des perfs API
  packages/api/db/migrations/000110-01-convert-localized_organizations-to-materialized-view.js
  packages/api/server/models/organizationModel.js
Labels: [validé]

#163 #patch (1047) Validation du linting sur chaque PR
  .github/workflows/check-lint.yml
  .husky/pre-push
  package.json
  packages/api/package.json
  packages/api/server/app.js
  packages/api/server/controllers/inviteController.js
  packages/api/server/controllers/townController.js
  packages/api/server/controllers/townController/addActor.js
  packages/api/server/controllers/townController/inviteNewActor.js
  packages/api/server/controllers/userController.js
  packages/frontend/.eslintrc
  packages/frontend/.lintstagedrc.js
  packages/frontend/jsconfig.json
  packages/frontend/package.json
  packages/frontend/src/js/app/components/ui/registerGlobalComponents.js
  packages/frontend/src/js/app/pages/TownDetails/TownDetails.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsActorThemesModal.vue
  packages/frontend/vue.config.js
  packages/frontend/yarn.lock
Labels: [validé]

#165 #minor (1025) Évolution de la cartographie
  packages/api/db/data/cities-with-lat-and-lon.csv
  packages/api/db/migrations/000107-01-insert-intervener-permissions.js
  packages/api/db/migrations/000111-01-alter-table-city-add-lat-lon.js
  packages/api/db/migrations/000111-02-populate-col-lat-long-table-cities.js
  packages/api/package.json
  packages/api/server/models/shantytownModel.js
  packages/frontend/package.json
  packages/frontend/src/geojson/departements.json
  packages/frontend/src/geojson/regions.json
  packages/frontend/src/js/app/components/map/map.js
  packages/frontend/src/js/app/pages/dashboard/dashboard.scss
  packages/frontend/yarn.lock
Labels: [qa], [à corriger]

#170 #patch (1090,1091) Ajout de nouveaux types de structure
  packages/api/db/migrations/000112-01-insert-organization_type-defenseur-des-droits.js
  packages/api/db/migrations/000112-02-insert-organization_type-ceser.js
Labels: [validé]

#171 (1048) Mise à jour de dépendances techniques
  packages/api/Dockerfile
  packages/api/package.json
  packages/api/server/controllers/townController.js
  packages/api/server/utils/excel.js
  packages/api/server/utils/mail.js
  packages/api/yarn.lock
  packages/frontend/Dockerfile
  packages/frontend/package.json
  packages/frontend/yarn.lock
Labels: [validé]

#174 #patch (992) Marquer le champ adresse obligatoire
  packages/frontend/src/js/app/components/TownForm/inputs/InputAddress.vue
Labels: [validé]

#175 #patch (1099) Lier la carto au store
  packages/frontend/src/js/app/pages/dashboard/dashboard.js
Labels: [validé]

#166 #patch (1032) Ajout de courbes d'évolution du nombre d'habitants
  packages/api/db/migrations/000113-01-fix-primary_key-shantytownOriginHistories.js
  packages/api/db/migrations/000113-02-fix-primary_key-shantytownClosingSolutionHistories.js
  packages/api/db/migrations/000113-03-add-column-uid-to-social_origins.js
  packages/api/server/controllers/townController/edit.js
  packages/api/server/models/statsModel.js
  packages/api/test/suites/server/controllers/townController/edit.spec.js
  packages/frontend/cypress/integration/towns.create-edit-delete-fromMinToMin.spec.js
  packages/frontend/cypress/support/commands/emptyDate.js
  packages/frontend/src/js/app/pages/PrivateStats/index.vue
Labels: [qa], [validé]

#177 #minor (1057) Demander comment l'utilisateur a connu la plateforme
  packages/api/db/migrations/000113-01-create-table-contact-form-referrals.js
  packages/api/server/controllers/contactController.js
  packages/api/server/middlewares/validators/createContact.js
  packages/api/server/models/contactFormReferralModel.js
  packages/api/test/suites/server/controllers/contactController/contact.spec.js
  packages/frontend/src/js/app/messages/fr/contactPage.json
  packages/frontend/src/js/app/pages/Contact/index.vue
Labels: [validé]

#178 #minor (982) Pouvoir s'inscrire à la newsletter sur la page d'accueil + afficher les 3 dernières newsletters
  packages/frontend/src/js/app/components/PublicLayout/PublicFooter.vue
  packages/frontend/src/js/app/components/ui/Button.vue
  packages/frontend/src/js/app/messages/fr/footer.json
  packages/frontend/src/js/app/messages/fr/landingPage.json
  packages/frontend/src/js/app/pages/LandingPage/LandingPageNewsletter.vue
  packages/frontend/src/js/app/pages/LandingPage/index.vue
  packages/frontend/src/js/app/pages/LandingPage/newsletters.js
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsPanelCharacteristics.vue
Labels: [validé]

#184 #patch (1087) Update couting method of WAU
  packages/frontend/src/js/app/pages/PrivateStats/index.vue
Labels: [en attente de review], [validé]

#182 #patch (693) Refactoring
  packages/api/server/controllers/townController.js
  packages/api/server/controllers/townController/edit.js
  packages/api/server/loaders/routesLoader.js
  packages/api/server/middlewares/validators/closeTown.js
  packages/api/server/middlewares/validators/common/writeTown.js
  packages/api/server/middlewares/validators/index.js
  packages/api/server/models/organizationModel.js
  packages/api/server/models/shantytownModel.js
  packages/api/server/services/shantytown/create.js
  packages/api/server/services/shantytown/index.js
  packages/api/server/utils/slack.js
  packages/api/test/suites/server/controllers/townController/close.spec.js
  packages/api/test/suites/server/controllers/townController/edit.spec.js
  packages/api/test/suites/server/models/shantytownModel.spec.js
  packages/api/test/utils/shantytownWatcher.js
  packages/frontend/src/js/app/components/TownForm/TownForm.vue
  packages/frontend/src/js/app/components/TownForm/TownFormErrorLog.vue
  packages/frontend/src/js/app/components/ui/Autocomplete.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCloseModal.vue
Labels: [en attente de review]

#181 #patch (693) Notification mail à l'ouverture et fermeture de sites
  packages/api/package.json
  packages/api/server/controllers/townController.js
  packages/api/server/controllers/townController/edit.js
  packages/api/server/loaders/routesLoader.js
  packages/api/server/mails/dist/user_shantytown_closed.html
  packages/api/server/mails/dist/user_shantytown_closed.subject.text
  packages/api/server/mails/dist/user_shantytown_closed.text
  packages/api/server/mails/dist/user_shantytown_declared.html
  packages/api/server/mails/dist/user_shantytown_declared.subject.text
  packages/api/server/mails/dist/user_shantytown_declared.text
  packages/api/server/mails/mails.js
  packages/api/server/mails/src/user_review.mjml
  packages/api/server/mails/src/user_shantytown_closed.mjml
  packages/api/server/mails/src/user_shantytown_declared.mjml
  packages/api/server/middlewares/validators/closeTown.js
  packages/api/server/middlewares/validators/common/writeTown.js
  packages/api/server/middlewares/validators/index.js
  packages/api/server/models/organizationModel.js
  packages/api/server/models/shantytownModel.js
  packages/api/server/models/userModel.js
  packages/api/server/services/shantytown/create.js
  packages/api/server/services/shantytown/index.js
  packages/api/server/utils/slack.js
  packages/api/test/suites/server/controllers/townController/close.spec.js
  packages/api/test/suites/server/controllers/townController/edit.spec.js
  packages/api/test/suites/server/models/shantytownModel.spec.js
  packages/api/test/utils/shantytownWatcher.js
  packages/api/yarn.lock
  packages/frontend/src/js/app/components/TownForm/TownForm.vue
  packages/frontend/src/js/app/components/TownForm/TownFormErrorLog.vue
  packages/frontend/src/js/app/components/ui/Autocomplete.vue
  packages/frontend/src/js/app/pages/TownDetails/TownDetailsCloseModal.vue
Labels: [qa]
